envLabel: stage

deployment:
  imageName: microservice-3
  imageTag: "latest"

service:
  name: project-a-ms-3

ingress:
  ingresses:
  - name: project-a-stage-ms-3
    rules:
    - host: app3-stage.ning-cicd.click
      path: /
      service: project-a-ms-3
      serviceport: 80