{{- if .Values.ingress.enabled }}
{{- with .Values.ingress }}
{{- range .ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ .name }}-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    
    ### SSL Settings
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:294983251197:certificate/74550ea5-3721-43e2-976a-9b48489bcd1b
    ### SSL Redirect Setting
    #alb.ingress.kubernetes.io/ssl-redirect: '443'
    ### External DNS - For creating a Record Set in Route53
    #external-dns.alpha.kubernetes.io/hostname: alb-path-base.ning-cicd.click

spec:
  ingressClassName: my-aws-ingress-class
  rules:
{{- range .rules }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Exact
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .serviceport }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}