envLabel: prod

deployment:
  imageName: microservice-1
  imageTag: "6c9f55f"

service:
  name: project-a-ms-1

ingress:
  ingresses:
  - name: project-a-prod-ms-1
    rules:
    - host: app1.ning-cicd.click
      path: /
      service: project-a-ms-1
      serviceport: 80