envLabel: dev

deployment:
  imageName: microservice-1
  imageTag: "d669d23"

service:
  name: project-a-ms-1

ingress:
  ingresses:
  - name: project-a-dev-ms-1
    rules:
    - host: app1-dev.ning-cicd.click
      path: /
      service: project-a-ms-1
      serviceport: 80