apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-microservice-2
  namespace: argocd
spec:
  destination:
    namespace: env-prod
    server: "https://kubernetes.default.svc"
  project: env-prod
  source:
    path: helm/Project-A/templates-1/
    repoURL: "https://github.com/dragonflly/cicd.git"
    targetRevision: prod
    helm:
      releaseName: ms-2
      valueFiles:
      - values.yaml
      - ../microservice-2/values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
