apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Allow manifests to deploy from the Git repos
  sourceRepos:
  - https://github.com/dragonflly/cicd.git

  # Only permit applications to deploy to the namespace in the cluster
  destinations:
  - namespace: env-dev
    server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-stage
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Allow manifests to deploy from the Git repos
  sourceRepos:
  - https://github.com/dragonflly/cicd.git

  # Only permit applications to deploy to the namespace in the cluster
  destinations:
  - namespace: env-stage
    server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-prod
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Allow manifests to deploy from the Git repos
  sourceRepos:
  - https://github.com/dragonflly/cicd.git

  # Only permit applications to deploy to the namespace in the cluster
  destinations:
  - namespace: env-prod
    server: https://kubernetes.default.svc

